services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: 
      - postgres
  app:
    build: .
    networks:
      - postgres
    depends_on:
      postgres: 
        condition: service_healthy
    env_file: .env
    ports:
      - "9010:9300"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  postgres:
    driver: bridge